version: 1
 
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run test
          command: 'ruby test_sum.rb'
 
workflows:
  version: 1
  workflows:
    jobs:
      - test